### PR TITLE
Bf/requirements

### PR DESCRIPTION
**Pull request by pauldmccarthy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Howdy,

This PR brings the conda requirements in line with those listed in the textual `pyproject.toml` file. This is required to avoid a situation where conda happily installs a set of packages which are compatible according to the conda requirements, but incompatible according to the setuptools requirements. This results in runtime errors when interacting with `pkg_resources`. 

Related: conda-forge/rich-feedstock#98

### CODE REVIEW

**Comment by pauldmccarthy** [comment]
@conda-forge-admin, please rerende

**Comment by pauldmccarthy** [comment]
@carlodri Anything I can do to move this along? It's causing broken environments ..

**Comment by carlodri** [comment]
Sorry for the late reply!

**Comment by pauldmccarthy** [comment]
Great, thanks for that!

**Pull request merged**
